import { AppLanguage } from '@/store/useLanguageStore';

const DICTIONARY: Record<AppLanguage, Record<string, string>> = {
  en: {},
  fr: {
    'Welcome to': 'Bienvenue dans',
    'Installation & Setup': 'Installation et Configuration',
    'Before writing code, set up your development environment.': 'Avant d\'écrire du code, configurez votre environnement de développement.',
    'Requirements': 'Prérequis',
    'A modern computer (Windows, macOS, or Linux)': 'Un ordinateur moderne (Windows, macOS ou Linux)',
    'A text editor — VS Code is recommended': 'Un éditeur de texte — VS Code est recommandé',
    'Terminal / command-line access': 'Accès au terminal / ligne de commande',
    'Installation Steps': 'Étapes d\'installation',
    'Step 1': 'Étape 1',
    'Step 2': 'Étape 2',
    'Step 3': 'Étape 3',
    'Step 4': 'Étape 4',
    'Step 5': 'Étape 5',
    'Overview': 'Aperçu',
    'Introduction': 'Introduction',
    'Summary': 'Résumé',
    'Key Takeaways': 'Points clés à retenir',
    'Best Practices': 'Meilleures pratiques',
    'Common Pitfalls': 'Pièges courants',
    'Code Example': 'Exemple de code',
    'Interactive Challenge': 'Défi interactif',
    'Basic Computer Programming': 'Programmation informatique de base',
    'Variables & Data Types': 'Variables et types de données',
    'Control Flow & Loops': 'Flux de contrôle et boucles',
    'Functions & Scope': 'Fonctions et portée',
    'Data Structures & Algorithms': 'Structures de données et algorithmes',
    'Object-Oriented Programming': 'Programmation orientée objet',
    'Complete and pass the Lesson Quiz to unlock the Next Lesson!': 'Complétez et réussissez le Quiz pour débloquer la leçon suivante !',
    'Quiz Passed ✓': 'Quiz Réussi ✓',
    'Lesson Quiz': 'Quiz de la leçon',
    'Code Editor': 'Éditeur de code',
    'My Notes': 'Mes notes',
    'AI Tutor': 'Tuteur IA',
  },
  es: {
    'Welcome to': 'Bienvenido a',
    'Installation & Setup': 'Instalación y Configuración',
    'Before writing code, set up your development environment.': 'Antes de escribir código, configura tu entorno de desarrollo.',
    'Requirements': 'Requisitos',
    'A modern computer (Windows, macOS, or Linux)': 'Una computadora moderna (Windows, macOS o Linux)',
    'A text editor — VS Code is recommended': 'Un editor de texto — Se recomienda VS Code',
    'Terminal / command-line access': 'Acceso a la terminal / línea de comandos',
    'Installation Steps': 'Pasos de instalación',
    'Step 1': 'Paso 1',
    'Step 2': 'Paso 2',
    'Step 3': 'Paso 3',
    'Step 4': 'Paso 4',
    'Step 5': 'Paso 5',
    'Overview': 'Visión general',
    'Introduction': 'Introducción',
    'Summary': 'Resumen',
    'Key Takeaways': 'Puntos clave',
    'Best Practices': 'Mejores prácticas',
    'Common Pitfalls': 'Errores comunes',
    'Code Example': 'Ejemplo de código',
    'Interactive Challenge': 'Desafío interactivo',
    'Basic Computer Programming': 'Programación Básica de Computadoras',
    'Variables & Data Types': 'Variables y Tipos de Datos',
    'Control Flow & Loops': 'Flujo de Control y Bucles',
    'Functions & Scope': 'Funciones y Alcance',
    'Data Structures & Algorithms': 'Estructuras de Datos y Algoritmos',
    'Object-Oriented Programming': 'Programación Orientada a Objetos',
    'Complete and pass the Lesson Quiz to unlock the Next Lesson!': '¡Completa y aprueba el cuestionario para desbloquear la siguiente lección!',
    'Quiz Passed ✓': 'Cuestionario Aprobado ✓',
    'Lesson Quiz': 'Cuestionario de la Lección',
    'Code Editor': 'Editor de Código',
    'My Notes': 'Mis Notas',
    'AI Tutor': 'Tutor IA',
  },
  de: {
    'Welcome to': 'Willkommen bei',
    'Installation & Setup': 'Installation & Einrichtung',
    'Before writing code, set up your development environment.': 'Bevor Sie Code schreiben, richten Sie Ihre Entwicklungsumgebung ein.',
    'Requirements': 'Voraussetzungen',
    'A modern computer (Windows, macOS, or Linux)': 'Ein moderner Computer (Windows, macOS oder Linux)',
    'A text editor — VS Code is recommended': 'Ein Texteditor — VS Code wird empfohlen',
    'Terminal / command-line access': 'Terminal- / Befehlszeilenzugriff',
    'Installation Steps': 'Installationsschritte',
    'Step 1': 'Schritt 1',
    'Step 2': 'Schritt 2',
    'Step 3': 'Schritt 3',
    'Step 4': 'Schritt 4',
    'Step 5': 'Schritt 5',
    'Overview': 'Übersicht',
    'Introduction': 'Einführung',
    'Summary': 'Zusammenfassung',
    'Key Takeaways': 'Wichtigste Erkenntnisse',
    'Best Practices': 'Best Practices',
    'Common Pitfalls': 'Häufige Fallstricke',
    'Code Example': 'Code-Beispiel',
    'Interactive Challenge': 'Interaktive Herausforderung',
    'Basic Computer Programming': 'Grundlegende Computerprogrammierung',
    'Variables & Data Types': 'Variablen & Datentypen',
    'Control Flow & Loops': 'Kontrollfluss & Schleifen',
    'Functions & Scope': 'Funktionen & Gültigkeitsbereich',
    'Data Structures & Algorithms': 'Datenstrukturen & Algorithmen',
    'Object-Oriented Programming': 'Objektorientierte Programmierung',
    'Complete and pass the Lesson Quiz to unlock the Next Lesson!': 'Schließen Sie das Quiz erfolgreich ab, um die nächste Lektion freizuschalten!',
    'Quiz Passed ✓': 'Quiz Bestanden ✓',
    'Lesson Quiz': 'Lektions-Quiz',
    'Code Editor': 'Code-Editor',
    'My Notes': 'Meine Notizen',
    'AI Tutor': 'KI-Tutor',
  },
  pt: {
    'Welcome to': 'Bem-vindo ao',
    'Installation & Setup': 'Instalação e Configuração',
    'Before writing code, set up your development environment.': 'Antes de escrever código, configure seu ambiente de desenvolvimento.',
    'Requirements': 'Requisitos',
    'A modern computer (Windows, macOS, or Linux)': 'Um computador moderno (Windows, macOS ou Linux)',
    'A text editor — VS Code is recommended': 'Um editor de texto — VS Code é recomendado',
    'Terminal / command-line access': 'Acesso ao terminal / linha de comando',
    'Installation Steps': 'Etapas de instalação',
    'Step 1': 'Etapa 1',
    'Step 2': 'Etapa 2',
    'Step 3': 'Etapa 3',
    'Step 4': 'Etapa 4',
    'Step 5': 'Etapa 5',
    'Overview': 'Visão Geral',
    'Introduction': 'Introdução',
    'Summary': 'Resumo',
    'Key Takeaways': 'Pontos Chave',
    'Best Practices': 'Melhores Práticas',
    'Common Pitfalls': 'Armadilhas Comuns',
    'Code Example': 'Exemplo de Código',
    'Interactive Challenge': 'Desafio Interativo',
    'Basic Computer Programming': 'Programação Básica de Computadores',
    'Variables & Data Types': 'Variáveis e Tipos de Dados',
    'Control Flow & Loops': 'Fluxo de Controle e Loops',
    'Functions & Scope': 'Funções e Escopo',
    'Data Structures & Algorithms': 'Estruturas de Dados e Algoritmos',
    'Object-Oriented Programming': 'Programação Orientada a Objetos',
    'Complete and pass the Lesson Quiz to unlock the Next Lesson!': 'Conclua e passe no questionário para desbloquear a próxima lição!',
    'Quiz Passed ✓': 'Questionário Aprovado ✓',
    'Lesson Quiz': 'Questionário da Lição',
    'Code Editor': 'Editor de Código',
    'My Notes': 'Minhas Notas',
    'AI Tutor': 'Tutor IA',
  },
};

/**
 * Translates lesson markdown content and headings according to the selected app language.
 */
export function translateContent(text: string, lang: AppLanguage): string {
  if (!text || lang === 'en') return text;

  let translated = text;
  const langDict = DICTIONARY[lang];

  if (langDict) {
    for (const [key, value] of Object.entries(langDict)) {
      if (translated.includes(key)) {
        translated = translated.replaceAll(key, value);
      }
    }
  }

  return translated;
}
